export const blogs = [
  { id: 1, author: 'Mark Twen', date: 'Today, 12:00', content: 'This is an awesome adventure that I had! Thanks!', rating: 5, category: 'Adventure', avatar: 'avatar1.png' },
  { id: 2, author: 'Katherine Johns', date: '5 days ago, 12:15', content: 'The place is very big. I lost the exit.', rating: 3, category: 'Adventure', avatar: 'avatar2.png' },
  { id: 3, author: 'Sally Robinson', date: 'Yesterday, 18:30', content: 'Something new for me. Drive and emotions only', rating: 4, category: 'Nature', avatar: 'avatar3.png' },
  { id: 4, author: 'Stevie', date: '2 days ago, 09:05', content: 'Something to be upgraded.', rating: 2, category: 'Fashion', avatar: 'avatar4.png' },
  { id: 5, author: 'Alice Johnson', date: '3 days ago, 10:30', content: 'I enjoyed the scenic views and peaceful atmosphere.', rating: 4, category: 'Modern', avatar: 'avatar5.png' },
  { id: 6, author: 'Tom Hanks', date: '4 days ago, 11:45', content: 'A wonderful experience in nature. Would love to visit again!', rating: 5, category: 'Nature', avatar: 'avatar6.png' },
  { id: 7, author: 'John Doe', date: '5 days ago, 14:20', content: 'The fashion show was breathtaking!', rating: 4, category: 'Fashion', avatar: 'avatar7.png' },
  { id: 8, author: 'Jane Smith', date: '6 days ago, 16:10', content: 'An adventurous day filled with thrilling activities.', rating: 5, category: 'Adventure', avatar: 'avatar8.png' },
  { id: 9, author: 'Chris Evans', date: 'A week ago, 09:30', content: 'Amazing architecture and modern designs everywhere.', rating: 4, category: 'Modern', avatar: 'avatar9.png' },
  { id: 10, author: 'Sarah Lee', date: '8 days ago, 13:50', content: 'The natural landscapes were just amazing. Totally recommend it!', rating: 5, category: 'Nature', avatar: 'avatar10.png' },
  { id: 11, author: 'Mike Johnson', date: '10 days ago, 17:25', content: 'A great place for adventure enthusiasts!', rating: 4, category: 'Adventure', avatar: 'avatar11.png' },
  { id: 12, author: 'Emily Clarke', date: '11 days ago, 12:45', content: 'A delightful fashion show with a lot of new trends.', rating: 5, category: 'Fashion', avatar: 'avatar12.png' },
  { id: 13, author: 'Robert Brown', date: '12 days ago, 08:15', content: 'Modern art and culture on display. Highly educational!', rating: 4, category: 'Modern', avatar: 'avatar13.png' },
  { id: 14, author: 'Laura Davis', date: '2 weeks ago, 15:40', content: 'Enjoyed the hike in nature. A great way to relax!', rating: 5, category: 'Nature', avatar: 'avatar14.png' },
  { id: 15, author: 'Peter Parker', date: '3 weeks ago, 11:30', content: 'A challenging adventure but worth every moment.', rating: 4, category: 'Adventure', avatar: 'avatar15.png' },
  { id: 16, author: 'Bruce Wayne', date: '3 weeks ago, 10:00', content: 'Fashion week was a blast! Amazing outfits and designs.', rating: 5, category: 'Fashion', avatar: 'avatar16.png' },
  { id: 17, author: 'Diana Prince', date: 'A month ago, 14:10', content: 'A tour of modern architecture and innovative designs.', rating: 4, category: 'Modern', avatar: 'avatar17.png' },
  { id: 18, author: 'Clark Kent', date: 'A month ago, 13:50', content: 'An adventure to remember! Thrilling activities throughout.', rating: 5, category: 'Adventure', avatar: 'avatar18.png' },
  { id: 19, author: 'Tony Stark', date: 'A month ago, 11:45', content: 'Loved the serene nature trails. A must-visit place!', rating: 5, category: 'Nature', avatar: 'avatar19.png' },
  { id: 20, author: 'Natasha Romanoff', date: '5 weeks ago, 12:30', content: 'Modern technology exhibition was mind-blowing.', rating: 4, category: 'Modern', avatar: 'avatar20.png' },
  { id: 21, author: 'Steve Rogers', date: '5 weeks ago, 09:10', content: 'An amazing place for an adventure with friends.', rating: 5, category: 'Adventure', avatar: 'avatar21.png' },
  { id: 22, author: 'Bruce Banner', date: '6 weeks ago, 14:25', content: 'A peaceful nature retreat. Very refreshing!', rating: 5, category: 'Nature', avatar: 'avatar22.png' },
  { id: 23, author: 'Carol Danvers', date: '6 weeks ago, 16:35', content: 'Fashion trends were highlighted well at the event.', rating: 4, category: 'Fashion', avatar: 'avatar23.png' }
];
